'use client';
import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BarChart3, CircleAlert, Package, Truck } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { profitability, rankProfit, supplierCatalog, type Metric, type ProfitRow } from '@/lib/domain/analytics';
import type { Workspace, Recipe } from '@/types/domain';
const euro=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(v);
const percent=(v:number)=>`${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(v)} %`;
const metrics:{value:Metric;label:string}[]=[{value:'margin_value',label:'Marge HT / portion (€)'},{value:'margin_rate',label:'Taux de marque (%)'},{value:'markup_rate',label:'Taux de marge (%)'},{value:'food_rate',label:'Taux de coût matière (%)'}];
function Filter({label,value,change,options}:{label:string;value:string;change:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={change}><SelectTrigger className="select-control" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
function Ranking({title,rows,metric,open,best}:{title:string;rows:ProfitRow[];metric:Metric;open:(r:Recipe)=>void;best:boolean}){return <section className="panel"><div className="panel-heading"><h2>{best?<ArrowUpRight size={18}/>:<ArrowDownRight size={18}/>} {title}</h2><span className="badge">{metrics.find(m=>m.value===metric)?.label}</span></div>{rows.length?rows.slice(0,3).map((r,i)=><button className="analysis-ranking" onClick={()=>open(r.recipe)} key={r.recipe.id}><span className="rank-number">{i+1}</span><span><strong>{r.recipe.name}</strong><small>{r.recipe.category||'Sans catégorie'}</small></span><strong className={r.margin_value<0?'analysis-negative':'teal'}>{r[metric]===null?'Non défini':metric==='margin_value'?euro(r[metric]):percent(r[metric])}</strong></button>):<p className="quiet-state">Aucune recette chiffrée pour ces filtres.</p>}</section>;}
export default function Analytics({state,open}:{state:Workspace;open:(r:Recipe)=>void}){
 const [category,setCategory]=useState('all'),[supplier,setSupplier]=useState('all'),[metric,setMetric]=useState<Metric>('margin_value'),[direction,setDirection]=useState('best'),[query,setQuery]=useState('');
 const analysis=profitability(state);
 const rows=analysis.rows.filter(r=>(category==='all'||r.recipe.category===category)&&(supplier==='all'||r.supplier_ids.includes(supplier))&&r.recipe.name.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')));
 const sorted=rankProfit(rows,metric,direction==='best');
 const best=rankProfit(rows.filter(r=>r[metric]!==null),metric,true),worst=rankProfit(rows.filter(r=>r[metric]!==null),metric,false);
 const catalog=supplierCatalog(state).filter(s=>supplier==='all'||s.supplier.id===supplier);
 const categoryOptions=[{value:'all',label:'Toutes les catégories'},...[...new Set(state.recipes.filter(r=>!r.deleted_at).map(r=>r.category).filter(Boolean))].map(c=>({value:c,label:c}))];
 const supplierOptions=[{value:'all',label:'Tous les fournisseurs'},...state.suppliers.filter(s=>!s.deleted_at).map(s=>({value:s.id,label:s.name}))];
 return <Tabs defaultValue="profit" className="analyses"><TabsList className="analysis-tabs"><TabsTrigger value="profit"><BarChart3/>Rentabilité</TabsTrigger><TabsTrigger value="purchases"><Truck/>Achats</TabsTrigger><TabsTrigger value="rotation"><Package/>Rotation des stocks</TabsTrigger></TabsList>
 <TabsContent value="profit"><div className="analysis-note"><BarChart3 size={19}/><p><strong>Rentabilité théorique par portion</strong><br/>Calculée aux prix actuels, hors frais fixes et commissions. Sans ventes, la marge totale réalisée et les meilleures ventes ne sont pas connues.</p></div>
 <div className="analysis-filters"><FieldSearch query={query} setQuery={setQuery}/><Filter label="Catégorie de recette" value={category} change={setCategory} options={categoryOptions}/><Filter label="Fournisseur de coût" value={supplier} change={setSupplier} options={supplierOptions}/><Filter label="Indicateur" value={metric} change={v=>setMetric(v as Metric)} options={metrics}/></div>
 <p className="analysis-caption">Le filtre fournisseur inclut les recettes utilisant au moins une de ses références de coût, y compris via une sous-recette. Les montants des recettes ne sont pas attribués à ce fournisseur.</p>
 <div className="analysis-kpis"><div className="stat"><small>Recettes comparables · filtre actif</small><strong>{rows.length}</strong><small>Prix de vente et coût renseignés</small></div><div className="stat"><small>Marge directe négative · filtre actif</small><strong className={rows.some(r=>r.margin_value<0)?'analysis-negative':''}>{rows.filter(r=>r.margin_value<0).length}</strong><small>Prix HT inférieur au coût direct</small></div><div className="stat"><small>Fiches exclues · tout le catalogue</small><strong>{analysis.excluded.length}</strong><small>Prix ou coût incomplet</small></div></div>
 <div className="analysis-rankings"><Ranking title="Top produits" rows={best} metric={metric} open={open} best/><Ranking title="Flop produits" rows={worst} metric={metric} open={open} best={false}/></div>
 <section className="panel data-panel"><div className="panel-heading"><h2>Comparer les recettes</h2><Filter label="Ordre" value={direction} change={setDirection} options={[{value:'best',label:'Plus favorable en premier'},{value:'worst',label:'Moins favorable en premier'}]}/></div><Table><TableHeader><TableRow><TableHead>Recette</TableHead><TableHead>Prix HT</TableHead><TableHead>Coût direct HT</TableHead><TableHead>Marge / portion</TableHead><TableHead>Taux de marque</TableHead><TableHead>Taux de marge</TableHead><TableHead>Coût matière</TableHead></TableRow></TableHeader><TableBody>{sorted.map(r=><TableRow key={r.recipe.id}><TableCell><button className="text-button" onClick={()=>open(r.recipe)}>{r.recipe.name}<ArrowUpRight size={14}/></button></TableCell><TableCell>{euro(r.price_ht)}</TableCell><TableCell>{euro(r.cost)}</TableCell><TableCell className={r.margin_value<0?'analysis-negative':'teal'}>{euro(r.margin_value)}</TableCell><TableCell>{percent(r.margin_rate)}</TableCell><TableCell>{r.markup_rate===null?'Non défini (coût nul)':percent(r.markup_rate)}</TableCell><TableCell>{percent(r.food_rate)}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="quiet-state">Aucune recette comparable. Complétez les prix ou modifiez les filtres.</p>}</section>
 <p className="analysis-caption">Taux de marque = marge / prix HT. Taux de marge = marge / coût direct HT. Le taux de coût matière le plus bas est classé en premier dans le top. Avec peu de recettes, top et flop peuvent contenir les mêmes produits.</p>
 {analysis.excluded.length>0&&<section className="panel"><div className="panel-heading"><h2>Fiches à compléter · tout le catalogue</h2></div>{analysis.excluded.map(e=><button className="analysis-ranking" key={e.recipe.id} onClick={()=>open(e.recipe)}><CircleAlert size={18}/><strong>{e.recipe.name}</strong><small>{e.reason}</small></button>)}</section>}
 </TabsContent>
 <TabsContent value="purchases"><div className="analysis-note"><Truck size={20}/><p><strong>Montants et volumes achetés : pas encore disponibles</strong><br/>Cette version contient des offres fournisseurs, pas des achats effectués. Le classement en euros et en quantités sera alimenté par les réceptions acceptées ; les commandes resteront des engagements séparés.</p></div><div className="analysis-filters compact"><Filter label="Fournisseur" value={supplier} change={setSupplier} options={supplierOptions}/></div><section className="panel data-panel"><div className="panel-heading"><h2>Catalogue par fournisseur</h2><span className="badge">Références proposées · pas des achats</span></div><Table><TableHeader><TableRow><TableHead>Fournisseur / article</TableHead><TableHead>Référence</TableHead><TableHead>Contenu par achat</TableHead><TableHead>Prix proposé HT</TableHead></TableRow></TableHeader><TableBody>{catalog.flatMap(s=>s.references.map(ref=><TableRow key={ref.id}><TableCell><strong>{s.supplier.name}</strong><small>{s.items.find(i=>i.id===ref.item_id)?.name}</small></TableCell><TableCell>{ref.code||'Sans code'}</TableCell><TableCell>{ref.pack_count} × {ref.content_quantity} {ref.content_unit==='piece'?'pièce':ref.content_unit} / {ref.packaging}</TableCell><TableCell>{euro(ref.price_ht)}</TableCell></TableRow>))}</TableBody></Table>{!catalog.some(s=>s.references.length)&&<p className="quiet-state">Aucune référence pour ce fournisseur.</p>}</section><p className="analysis-caption">Les futurs volumes seront normalisés et classés séparément en kg, litres et pièces. Aucun total ne mélangera ces unités. Les filtres de période et d’établissement seront ajoutés avec les données opérationnelles.</p></TabsContent>
 <TabsContent value="rotation"><section className="panel analysis-unavailable"><Package size={32}/><h2>Identifier les stocks dormants</h2><p>Il n’y a pas encore d’inventaires ni de mouvements de stock dans cette version. La rotation, la valeur immobilisée et les jours de couverture ne peuvent pas être calculés.</p><div className="analysis-rules"><div><strong>Stock dormant</strong><p>Stock positif et absence de consommation sur une période suffisamment documentée.</p></div><div><strong>Faible rotation</strong><p>Consommation faible par rapport au stock disponible, selon un seuil propre à l’article.</p></div><div><strong>À vérifier</strong><p>Inventaires trop anciens ou données insuffisantes. Aucune conclusion tirée de la seule absence de commande.</p></div></div><p>À raccorder : inventaires validés, réceptions acceptées, transferts, fabrications et pertes. La consommation apparente restera distincte des ventes.</p></section></TabsContent>
 </Tabs>;
}
function FieldSearch({query,setQuery}:{query:string;setQuery:(v:string)=>void}){return <label className="field"><span>Rechercher une recette</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom de la recette…"/></label>;}
